---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: ujammy-${BUILD_NUMBER}-${JOB_NAME}
    region: eu-central-1
    image: ami-0a87a69d69fa289be
    vpc_subnet_id: subnet-0fad4db6fdd8025b6
    instance_type: t2.small
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pg-worker
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../../playbooks/prepare.yml
    cleanup: ../../playbooks/cleanup-deb.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: testinfra
  directory: ../../../tests/tests_meta_server
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
