---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: ppt-ufocal-${BUILD_NUMBER}
    region: eu-central-1
    image: ami-0fd8f89f28610e525
    vpc_subnet_id: subnet-085deaca8c1c59a4f
    instance_type: t2.xlarge
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pg-worker
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: ansible
scenario:
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - destroy
