---
  - name: Setting facts so that they will be persisted in the fact cache
    set_fact:
      major_version: "{{ lookup('env', 'VERSION').split('.')[0].split('-')[1] }}"
      repo: "{{ lookup('env', 'PDP_REPO') }}"
      version: "{{ lookup('env', 'PDP_BRANCH') }}"
      pgbench_scale: "{{ lookup('env', 'PGBENCH_SCALE') }}"
      pgbench_duration: "{{ lookup('env', 'PGBENCH_DURATION') }}"
      pgbench_clients: "{{ lookup('env', 'PGBENCH_CLIENTS') }}"
      pgbench_threads: "{{ lookup('env', 'PGBENCH_THREADS') }}"
      run_heap: "{{ lookup('env', 'RUN_HEAP') }}"
      run_tde_heap: "{{ lookup('env', 'RUN_TDE_HEAP') }}"
      run_tde_heap_basic: "{{ lookup('env', 'RUN_TDE_HEAP_BASIC') }}"
      #change_tde_branch: "{{ lookup('env', 'CHANGE_TDE_BRANCH') }}"
      tde_branch: "{{ lookup('env', 'TDE_BRANCH') }}"
      cacheable: true

  - name: Include Redhat tasks file
    include_tasks: 
      file: "redhat_tasks.yml"
    when: ansible_os_family == 'RedHat'

  - name: Include Debian tasks file
    include_tasks: 
      file: "debian_tasks.yml"
    when: ansible_os_family == 'Debian'

       # // choice name: 'PLATFORM'
       # // choice name: 'REPO'
       # string name: 'VERSION' 
       # string name: 'PDP_REPO' 
       # string name: 'PDP_BRANCH' 
       # booleanParam name: 'INSTALL_SERVER_FROM_PACKAGES' 
       # string name: 'PGBENCH_SCALE'
       # string 'PGBENCH_DURATION'
       # string name: 'PGBENCH_CLIENTS'
       # string name: 'PGBENCH_THREADS'
       # booleanParam name: 'RUN_HEAP'
       # booleanParam name: 'RUN_TDE_HEAP'
       # booleanParam name: 'RUN_TDE_HEAP_BASIC'
       # string name: 'TDE_BRANCH'
