---

  - name: Configure repository
    include_tasks: ../../../../tasks/enable_repo.yml

  - name: Include tasks based on OS family
      include_tasks: "{{ 'redhat_tasks.yml' if ansible_os_family == 'RedHat' else 'debian_tasks.yml' if ansible_os_family == 'Debian'}}"
